resources:
  Dbp\Relay\FormalizeBundle\Entity\Submission:
    types: ['https://schema.org/DataFeed']
    shortName: "FormalizeSubmission"
    normalizationContext:
      groups: ["FormalizeSubmission:output"]
      jsonld_embed_context: true
      preserve_empty_objects: true
    denormalizationContext:
      groups: ["FormalizeSubmission:input"]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        uriTemplate: "/formalize/submissions/{identifier}"
        openapiContext:
          tags: ["Formalize"]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        uriTemplate: "/formalize/submissions"
        openapiContext:
          tags: ["Formalize"]
          summary: Retrieves the collection of FormalizeSubmission resources for the specified FormalizeForm resource.
          parameters:
            - name: formIdentifier
              in: query
              description: 'The identifier of the FormalizeForm resource to get submissions for'
              type: string
            - name: outputValidation
              in: query
              description: | 
                The output validation filter to apply:
                * NONE: Don't apply an output validation filter (default)
                * KEYS: Only return submissions whose keys match those of the form schema
              type: string
              default: NONE
              schema:
                type: string
                enum:
                  - NONE
                  - KEYS

      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions"
        inputFormats:
          jsonld: [ 'application/ld+json' ]
          json: [ 'application/json' ]
        outputFormats:
          jsonld: [ 'application/ld+json' ]
          json: [ 'application/json' ]
        openapiContext:
          tags: ["Formalize"]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    form:
                      type: "string"
                      example: "/formalize/forms/7432af11-6f1c-45ee-8aa3-e90b3395e29c"
                    dataFeedElement:
                      type: "string"
                      deprecated: true
                    data:
                      type: "object"
                      example:
                        firstname: "Joni"
                        lastname: "Doe"
                  required:
                    - form
                    - data
      ApiPlatform\Metadata\Patch:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions/{identifier}"
        inputFormats:
          json: [ 'application/merge-patch+json' ]
        openapiContext:
          tags: [ "Formalize" ]
          requestBody:
            content:
              application/merge-patch+json:
                schema:
                  type: "object"
                  properties:
                    form:
                      type: "string"
                    dataFeedElement:
                      type: "string"
                example:
                  dataFeedElement: '{"firstname": "Johann", "lastname": "Dodl"}'
      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
      delete_by_form_identifier:
        class: ApiPlatform\Metadata\Delete
        method: DELETE
        controller: Dbp\Relay\FormalizeBundle\Rest\RemoveAllFormSubmissionsController
        uriTemplate: "/formalize/submissions"
        openapiContext:
          tags: [ "Formalize" ]
          summary: Deletes all submissions of a FormalizeForm resource.
          parameters:
            - name: formIdentifier
              in: query
              description: 'The identifier of the FormalizeForm resource to delete submissions for'
              type: string
              required: true
    properties:
      data:
        openapiContext:
          type: "object"
          properties:
            firstname:
              type: "string"
            lastname:
              type: "string"
        jsonSchemaContext:
          type: "object"
          properties:
            firstname:
              type: "string"
            lastname:
              type: "string"

  Dbp\Relay\FormalizeBundle\Entity\Form:
    types: [ 'https://schema.org/Dataset' ]
    shortName: "FormalizeForm"
    normalizationContext:
      groups: [ "FormalizeForm:output" ]
      jsonld_embed_context: true
    denormalizationContext:
      groups: [ "FormalizeForm:input" ]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms"
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        uriTemplate: "/formalize/forms"
        openapiContext:
          tags: [ "Formalize" ]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                  required:
                    - name
                example:
                  name: "My Form"
      ApiPlatform\Metadata\Patch:
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms/{identifier}"
        inputFormats:
          json: [ 'application/merge-patch+json' ]
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        uriTemplate: "/formalize/forms/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
