resources:
  Dbp\Relay\FormalizeBundle\Entity\Submission:
    types: ['https://schema.org/DataFeed']
    shortName: "FormalizeSubmission"
    normalizationContext:
      groups: ["FormalizeSubmission:output"]
      jsonld_embed_context: true
    denormalizationContext:
      groups: ["FormalizeSubmission:input"]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        uriTemplate: "/formalize/submissions/{identifier}"
        openapiContext:
          tags: ["Formalize"]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        uriTemplate: "/formalize/submissions"
        openapiContext:
          tags: ["Formalize"]
          parameters:
            - name: formIdentifier
              in: query
              description: 'The identifier of the FormalizeForm to get submissions for'
              type: string
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions"
        openapiContext:
          tags: ["Formalize"]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    form:
                      type: "string"
                    dataFeedElement:
                      type: "string"
                  required:
                    - form
                example:
                  form: "/formalize/forms/7432af11-6f1c-45ee-8aa3-e90b3395e29c"
                  dataFeedElement: '{"firstname": "John", "lastname": "Doe"}'
      ApiPlatform\Metadata\Patch:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    form:
                      type: "string"
                    dataFeedElement:
                      type: "string"
                example:
                  dataFeedElement: '{"firstname": "Johann", "lastname": "Dodl"}'
      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\FormalizeBundle\Rest\SubmissionProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\SubmissionProcessor
        uriTemplate: "/formalize/submissions/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
    properties:
      identifier:
        identifier: true
      dataFeedElement:
        iri: 'https://schema.org/DataFeed'
      form:
        iri: 'https://schema.org/Text'
      dateCreated:
        iri: 'https://schema.org/dateCreated'

  Dbp\Relay\FormalizeBundle\Entity\Form:
    types: [ 'https://schema.org/Dataset' ]
    shortName: "FormalizeForm"
    normalizationContext:
      groups: [ "FormalizeForm:output" ]
      jsonld_embed_context: true
    denormalizationContext:
      groups: [ "FormalizeForm:input" ]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms"
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        uriTemplate: "/formalize/forms"
        openapiContext:
          tags: [ "Formalize" ]
          requestBody:
            content:
              application/ld+json:
                schema:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                  required:
                    - name
                example:
                  name: "My Form"
      ApiPlatform\Metadata\Patch:
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        uriTemplate: "/formalize/forms/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
      ApiPlatform\Metadata\Delete:
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        uriTemplate: "/formalize/forms/{identifier}"
        openapiContext:
          tags: [ "Formalize" ]
      delete_form_submissions:
        class: ApiPlatform\Metadata\Delete
        method: DELETE
        provider: Dbp\Relay\FormalizeBundle\Rest\FormProvider
        processor: Dbp\Relay\FormalizeBundle\Rest\FormProcessor
        uriTemplate: "/formalize/forms/{identifier}/clear"
        openapiContext:
          tags: [ "Formalize" ]
          summary: Deletes all submissions of the FormalizeForm resource.
    properties:
      identifier:
        identifier: true
        iri: 'https://schema.org/identifier'
      name:
        iri: 'https://schema.org/name'
      dataFeedSchema:
        iri: 'https://schema.org/additionalData'
      availabilityStarts:
        iri: 'https://schema.org/availabilityStarts'
      availabilityEnds:
        iri: 'https://schema.org/availabilityEnds'
      readFormUsersOption:
        iri: 'https://schema.org/additionalProperty'
      addSubmissionsUsersOption:
        iri: 'https://schema.org/additionalProperty'
      readSubmissionsUsersOption:
        iri: 'https://schema.org/additionalProperty'
      writeSubmissionsUsersOption:
        iri: 'https://schema.org/additionalProperty'
