services:
  Dbp\Relay\FormalizeBundle\Command\TestCommand:
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Event\:
    resource: '../../Event'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\DataPersister\:
    resource: '../../DataPersister'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\DataProvider\:
    resource: '../../DataProvider'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Service\FormalizeService:
    autowire: true
    autoconfigure: true
    arguments:
      $em: '@doctrine.orm.dbp_relay_formalize_bundle_entity_manager'

  Dbp\Relay\FormalizeBundle\HealthCheck\HealthCheck:
    autowire: true
    autoconfigure: true