services:
  Dbp\Relay\FormalizeBundle\Event\:
    resource: '../../Event'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\EventSubscriber\:
    resource: '../../EventSubscriber'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Rest\:
    resource: '../../Rest'
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Service\FormalizeService:
    autowire: true
    autoconfigure: true
    public: true
    arguments:
      $entityManager: '@doctrine.orm.dbp_relay_formalize_bundle_entity_manager'

  Dbp\Relay\FormalizeBundle\HealthCheck\HealthCheck:
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Authorization\AuthorizationService:
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Rest\RemoveAllFormSubmissionsController:
    autowire: true
    autoconfigure: true

  Dbp\Relay\FormalizeBundle\Command\:
    resource: '../../Command'
    autowire: true
    autoconfigure: true
